# Python

1.Write a program using list comprehension to find primes 
in range 2 to 100.

In [5]:


primes = [num for num in range(2,100) if 0 not in [num%i for i in range(2,num//2)]]

print (primes)

[2, 3, 4, 5, 7, 11, 13, 17, 19, 23, 29, 31, 37, 41, 43, 47, 53, 59, 61, 67, 71, 73, 79, 83, 89, 97]


2.Write a function to reverse a string

string='reverse a string'

In [15]:
def reversestr(string):
    string = string[::-1]
    return string
 
s = "reverse a string"
 
print("The given string is : ")
print(s)
 
str=reversestr(s)

print("The reversed string is : ", str)

# print(reverse(s))

The given string is : 
reverse a string
The reversed string is :  gnirts a esrever


3.Write a program to extract the words from the given list which have their first character in uppercase. Days = ['Monday', 'tuesday','friday', 'Sunday', 'Saturday']

Output: ['Monday', 'Sunday', 'Saturday'

In [1]:
Days = ['Monday', 'tuesday','friday', 'Sunday', 'Saturday']

print(Days)
print()
for i in Days:
    if i[0].isupper():
        print(i)
    

['Monday', 'tuesday', 'friday', 'Sunday', 'Saturday']

Monday
Sunday
Saturday


4.Write a program to extract the year part from the dates in 
the given list.

Batch = ['15-06-1997','15-06-2011','15-06-1993','15-06-2020']

Output: ['1997','2011','1993','2020']

In [19]:
Batch = ['15-06-1997','15-06-2011','15-06-1993','15-06-2020']
year = [x.split('-')[2] for x in Batch]
print('Years are: ',year)

Years are:  ['1997', '2011', '1993', '2020']


5.Write a program swap the keys to values and values to keys of the given dictionary. 

Module = {'Data Science':1,'Machine Learning':2, 'SQL':3, 'Big Data':4} 

Output: {1:'Data Science',2:'Machine Learning', 3:'SQL', 4:'Big Data'}

In [15]:

Module = {'Data Science':1,'Machine Learning':2, 'SQL':3, 'Big Data':4}
# output = {}
print("original dictionary is :",Module)
print()

output = dict([(v, [k for k, v1 in Module.items() if v1 == v])
for v in set(Module.values())])

print("swaped dictionary is:",output)


original dictionary is : {'Data Science': 1, 'Machine Learning': 2, 'SQL': 3, 'Big Data': 4}

swaped dictionary is: {1: ['Data Science'], 2: ['Machine Learning'], 3: ['SQL'], 4: ['Big Data']}


6.Write a program to count the number of elements in the string (given by the user) that are not present in the 'my_string'. 

Do not count the white spaces.

my_string = 'Data Science'

7.Define a function to check whether a number is in a range (1000,10000) or not.

In [4]:
def rangecheck(n):
    
    if n in range(1000,10000) :
        print(n, " is in the range between 1000 to 10000: ")
    else :
        print("The number is outside the given range.")
rangecheck(int(input("take a number: ")))


take a number: 1234
1234  is in the range between 1000 to 10000: 


8.Write a program to calculate the sum of all elements in the list.

test_score = [10, 32, 23, 14, 25]

In [ ]:

test_score = [10, 32, 23, 14, 25]
add= 0

for i in range(0, len(test_score)):
add=add + test_score[i]
  
print("Sum of all elements in given list: ", add)

9.Replace all even numbers in the array with -1.

Use the array given below num_array = np.array([0, 21, 32, 13, 44, 45, 26, 28, 38, 34, 65, 48, 76])

In [4]:
import numpy as np

In [9]:
# array = np.array([0, 21, 32, 13, 44, 45, 26, 28, 38, 34, 65, 48, 76])

In [14]:
array = np.array([0, 21, 32, 13, 44, 45, 26, 28, 38, 34, 65, 48, 76])
for i in range(len(array)):
 
    
    if array[i]%2 ==0 :
        array[i] = '-1'
        print(array)
        
 
    
 

[-1 21 32 13 44 45 26 28 38 34 65 48 76]
[-1 21 -1 13 44 45 26 28 38 34 65 48 76]
[-1 21 -1 13 -1 45 26 28 38 34 65 48 76]
[-1 21 -1 13 -1 45 -1 28 38 34 65 48 76]
[-1 21 -1 13 -1 45 -1 -1 38 34 65 48 76]
[-1 21 -1 13 -1 45 -1 -1 -1 34 65 48 76]
[-1 21 -1 13 -1 45 -1 -1 -1 -1 65 48 76]
[-1 21 -1 13 -1 45 -1 -1 -1 -1 65 -1 76]
[-1 21 -1 13 -1 45 -1 -1 -1 -1 65 -1 -1]


In [ ]:
array = np.array([0, 21, 32, 13, 44, 45, 26, 28, 38, 34, 65, 48, 76])

print("Enter the String: ")
str = int(input())
print("Enter the old character to search for: ")
oldchar = int(input(if array[i]%2 ==0 :))
print("Enter the new character to replace with: ")
newchar = int(input(-1))

str = str.replace(oldchar, newchar)
print("\nThe new string is: ")
print(str)

10.Find the minimum value along each of the rows. 

Create a 2D Numpy array from list of lists 

Score = np.array([[210, 402, 383], [140, 375, 106], [140, 125, 217], [292, 240, 295]])

In [17]:
import numpy as np

In [2]:
Score = np.array([[210, 402, 383], [140, 375, 106], [140, 125, 217], [292, 240, 295]])
Score

array([[210, 402, 383],
       [140, 375, 106],
       [140, 125, 217],
       [292, 240, 295]])

In [5]:
mini=Score.min(axis=1)
print(mini)

[210 106 125 240]
